// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJI8GzThNBMrdIcC4psB5O9lil__P2ryY',
    appId: '1:925910089590:web:da3c1dd4ba79c4ef138457',
    messagingSenderId: '925910089590',
    projectId: 'zenmate-e5da8',
    authDomain: 'zenmate-e5da8.firebaseapp.com',
    storageBucket: 'zenmate-e5da8.appspot.com',
    measurementId: 'G-6LWDS0EQE0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBD7_Y3thUJ-LNMB47BMEbVOpnnvbyzy4',
    appId: '1:925910089590:android:b1948568d56aea81138457',
    messagingSenderId: '925910089590',
    projectId: 'zenmate-e5da8',
    storageBucket: 'zenmate-e5da8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3QAEldrH8UQzro9ncmg8dT4z-82YqmGg',
    appId: '1:925910089590:ios:e869e39550f35bee138457',
    messagingSenderId: '925910089590',
    projectId: 'zenmate-e5da8',
    storageBucket: 'zenmate-e5da8.appspot.com',
    iosBundleId: 'com.example.mentalWellnessApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3QAEldrH8UQzro9ncmg8dT4z-82YqmGg',
    appId: '1:925910089590:ios:e869e39550f35bee138457',
    messagingSenderId: '925910089590',
    projectId: 'zenmate-e5da8',
    storageBucket: 'zenmate-e5da8.appspot.com',
    iosBundleId: 'com.example.mentalWellnessApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCJI8GzThNBMrdIcC4psB5O9lil__P2ryY',
    appId: '1:925910089590:web:513abf212a1cf07e138457',
    messagingSenderId: '925910089590',
    projectId: 'zenmate-e5da8',
    authDomain: 'zenmate-e5da8.firebaseapp.com',
    storageBucket: 'zenmate-e5da8.appspot.com',
    measurementId: 'G-HGDKDY0QDX',
  );
}
